// This file is autogenerated by the hyperschema compiler
// Schema Version: 2
/* eslint-disable camelcase */
/* eslint-disable quotes */
/* eslint-disable space-before-function-paren */

import { c } from 'hyperschema/runtime'

const VERSION = 2

// eslint-disable-next-line no-unused-vars
let version = VERSION

// @autobonk/writer
const encoding0 = {
  preencode(state, m) {
    c.buffer.preencode(state, m.key)
    state.end++ // max flag is 1 so always one byte
  },
  encode(state, m) {
    const flags = m.isIndexer ? 1 : 0

    c.buffer.encode(state, m.key)
    c.uint.encode(state, flags)
  },
  decode(state) {
    const r0 = c.buffer.decode(state)
    const flags = c.uint.decode(state)

    return {
      key: r0,
      isIndexer: (flags & 1) !== 0
    }
  }
}

// @autobonk/invite.roles
const encoding1_4 = c.array(c.string)

// @autobonk/invite
const encoding1 = {
  preencode(state, m) {
    c.buffer.preencode(state, m.id)
    c.buffer.preencode(state, m.invite)
    c.buffer.preencode(state, m.publicKey)
    c.int.preencode(state, m.expires)
    state.end++ // max flag is 8 so always one byte

    if (m.roles) encoding1_4.preencode(state, m.roles)
    if (m.createdBy) c.buffer.preencode(state, m.createdBy)
    if (m.createdAt) c.uint.preencode(state, m.createdAt)
    if (m.revokedAt) c.uint.preencode(state, m.revokedAt)
  },
  encode(state, m) {
    const flags =
      (m.roles ? 1 : 0) | (m.createdBy ? 2 : 0) | (m.createdAt ? 4 : 0) | (m.revokedAt ? 8 : 0)

    c.buffer.encode(state, m.id)
    c.buffer.encode(state, m.invite)
    c.buffer.encode(state, m.publicKey)
    c.int.encode(state, m.expires)
    c.uint.encode(state, flags)

    if (m.roles) encoding1_4.encode(state, m.roles)
    if (m.createdBy) c.buffer.encode(state, m.createdBy)
    if (m.createdAt) c.uint.encode(state, m.createdAt)
    if (m.revokedAt) c.uint.encode(state, m.revokedAt)
  },
  decode(state) {
    const r0 = c.buffer.decode(state)
    const r1 = c.buffer.decode(state)
    const r2 = c.buffer.decode(state)
    const r3 = c.int.decode(state)
    const flags = c.uint.decode(state)

    return {
      id: r0,
      invite: r1,
      publicKey: r2,
      expires: r3,
      roles: (flags & 1) !== 0 ? encoding1_4.decode(state) : null,
      createdBy: (flags & 2) !== 0 ? c.buffer.decode(state) : null,
      createdAt: (flags & 4) !== 0 ? c.uint.decode(state) : 0,
      revokedAt: (flags & 8) !== 0 ? c.uint.decode(state) : 0
    }
  }
}

// @autobonk/revoke-invite
const encoding2 = {
  preencode(state, m) {
    c.buffer.preencode(state, m.id)
    c.uint.preencode(state, m.revokedAt)
  },
  encode(state, m) {
    c.buffer.encode(state, m.id)
    c.uint.encode(state, m.revokedAt)
  },
  decode(state) {
    const r0 = c.buffer.decode(state)
    const r1 = c.uint.decode(state)

    return {
      id: r0,
      revokedAt: r1
    }
  }
}

// @autobonk/context-init
const encoding3 = {
  preencode(state, m) {
    c.buffer.preencode(state, m.creatorKey)
    c.uint.preencode(state, m.index)
    c.uint.preencode(state, m.timestamp)
  },
  encode(state, m) {
    c.buffer.encode(state, m.creatorKey)
    c.uint.encode(state, m.index)
    c.uint.encode(state, m.timestamp)
  },
  decode(state) {
    const r0 = c.buffer.decode(state)
    const r1 = c.uint.decode(state)
    const r2 = c.uint.decode(state)

    return {
      creatorKey: r0,
      index: r1,
      timestamp: r2
    }
  }
}

// @autobonk/role-def.permissions
const encoding4_1 = encoding1_4

// @autobonk/role-def
const encoding4 = {
  preencode(state, m) {
    c.string.preencode(state, m.name)
    encoding4_1.preencode(state, m.permissions)
    c.uint.preencode(state, m.rev)
    c.uint.preencode(state, m.index)
    c.uint.preencode(state, m.timestamp)
  },
  encode(state, m) {
    c.string.encode(state, m.name)
    encoding4_1.encode(state, m.permissions)
    c.uint.encode(state, m.rev)
    c.uint.encode(state, m.index)
    c.uint.encode(state, m.timestamp)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const r1 = encoding4_1.decode(state)
    const r2 = c.uint.decode(state)
    const r3 = c.uint.decode(state)
    const r4 = c.uint.decode(state)

    return {
      name: r0,
      permissions: r1,
      rev: r2,
      index: r3,
      timestamp: r4
    }
  }
}

// @autobonk/acl-entry.roles
const encoding5_1 = encoding1_4

// @autobonk/acl-entry
const encoding5 = {
  preencode(state, m) {
    c.buffer.preencode(state, m.subjectKey)
    encoding5_1.preencode(state, m.roles)
    c.uint.preencode(state, m.rev)
    c.uint.preencode(state, m.index)
    c.uint.preencode(state, m.timestamp)
  },
  encode(state, m) {
    c.buffer.encode(state, m.subjectKey)
    encoding5_1.encode(state, m.roles)
    c.uint.encode(state, m.rev)
    c.uint.encode(state, m.index)
    c.uint.encode(state, m.timestamp)
  },
  decode(state) {
    const r0 = c.buffer.decode(state)
    const r1 = encoding5_1.decode(state)
    const r2 = c.uint.decode(state)
    const r3 = c.uint.decode(state)
    const r4 = c.uint.decode(state)

    return {
      subjectKey: r0,
      roles: r1,
      rev: r2,
      index: r3,
      timestamp: r4
    }
  }
}

// @facebonk/profile
const encoding6 = {
  preencode(state, m) {
    c.string.preencode(state, m.id)
    state.end++ // max flag is 8 so always one byte

    if (m.displayName) c.string.preencode(state, m.displayName)
    if (m.bio) c.string.preencode(state, m.bio)
    c.uint.preencode(state, m.updatedAt)
    if (version >= 2 && m.avatar) encoding8.preencode(state, m.avatar)
    if (version >= 2 && m.avatarMimeType) c.string.preencode(state, m.avatarMimeType)
  },
  encode(state, m) {
    const flags =
      (m.displayName ? 1 : 0) |
      (m.bio ? 2 : 0) |
      ((version >= 2 && m.avatar) ? 4 : 0) |
      ((version >= 2 && m.avatarMimeType) ? 8 : 0)

    c.string.encode(state, m.id)
    c.uint.encode(state, flags)

    if (m.displayName) c.string.encode(state, m.displayName)
    if (m.bio) c.string.encode(state, m.bio)
    c.uint.encode(state, m.updatedAt)
    if (version >= 2 && m.avatar) encoding8.encode(state, m.avatar)
    if (version >= 2 && m.avatarMimeType) c.string.encode(state, m.avatarMimeType)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const flags = c.uint.decode(state)

    return {
      id: r0,
      displayName: (flags & 1) !== 0 ? c.string.decode(state) : null,
      bio: (flags & 2) !== 0 ? c.string.decode(state) : null,
      updatedAt: c.uint.decode(state),
      avatar: (version >= 2 && (flags & 4) !== 0) ? encoding8.decode(state) : null,
      avatarMimeType: (version >= 2 && (flags & 8) !== 0) ? c.string.decode(state) : null
    }
  }
}

// @facebonk/profile-set
const encoding7 = {
  preencode(state, m) {
    state.end++ // max flag is 64 so always one byte

    if (m.displayName) c.string.preencode(state, m.displayName)
    if (m.bio) c.string.preencode(state, m.bio)
    c.uint.preencode(state, m.updatedAt)
    if (version >= 2 && m.avatar) encoding8.preencode(state, m.avatar)
    if (version >= 2 && m.avatarMimeType) c.string.preencode(state, m.avatarMimeType)
  },
  encode(state, m) {
    const flags =
      (m.displayName ? 1 : 0) |
      (m.bio ? 2 : 0) |
      (m.clearDisplayName ? 4 : 0) |
      (m.clearBio ? 8 : 0) |
      ((version >= 2 && m.avatar) ? 16 : 0) |
      ((version >= 2 && m.avatarMimeType) ? 32 : 0) |
      ((version >= 2 && m.clearAvatar) ? 64 : 0)

    c.uint.encode(state, flags)

    if (m.displayName) c.string.encode(state, m.displayName)
    if (m.bio) c.string.encode(state, m.bio)
    c.uint.encode(state, m.updatedAt)
    if (version >= 2 && m.avatar) encoding8.encode(state, m.avatar)
    if (version >= 2 && m.avatarMimeType) c.string.encode(state, m.avatarMimeType)
  },
  decode(state) {
    const flags = c.uint.decode(state)

    return {
      displayName: (flags & 1) !== 0 ? c.string.decode(state) : null,
      bio: (flags & 2) !== 0 ? c.string.decode(state) : null,
      clearDisplayName: (flags & 4) !== 0,
      clearBio: (flags & 8) !== 0,
      updatedAt: c.uint.decode(state),
      avatar: (version >= 2 && (flags & 16) !== 0) ? encoding8.decode(state) : null,
      avatarMimeType: (version >= 2 && (flags & 32) !== 0) ? c.string.decode(state) : null,
      clearAvatar: (version >= 2 && (flags & 64) !== 0)
    }
  }
}

// @facebonk/blob
const encoding8 = {
  preencode(state, m) {
    c.fixed32.preencode(state, m.key)
    c.uint.preencode(state, m.blockOffset)
    c.uint.preencode(state, m.blockLength)
    c.uint.preencode(state, m.byteOffset)
    c.uint.preencode(state, m.byteLength)
  },
  encode(state, m) {
    c.fixed32.encode(state, m.key)
    c.uint.encode(state, m.blockOffset)
    c.uint.encode(state, m.blockLength)
    c.uint.encode(state, m.byteOffset)
    c.uint.encode(state, m.byteLength)
  },
  decode(state) {
    const r0 = c.fixed32.decode(state)
    const r1 = c.uint.decode(state)
    const r2 = c.uint.decode(state)
    const r3 = c.uint.decode(state)
    const r4 = c.uint.decode(state)

    return {
      key: r0,
      blockOffset: r1,
      blockLength: r2,
      byteOffset: r3,
      byteLength: r4
    }
  }
}

function setVersion(v) {
  version = v
}

function encode(name, value, v = VERSION) {
  version = v
  return c.encode(getEncoding(name), value)
}

function decode(name, buffer, v = VERSION) {
  version = v
  return c.decode(getEncoding(name), buffer)
}

function getEnum(name) {
  switch (name) {
    default:
      throw new Error('Enum not found ' + name)
  }
}

function getEncoding(name) {
  switch (name) {
    case '@autobonk/writer':
      return encoding0
    case '@autobonk/invite':
      return encoding1
    case '@autobonk/revoke-invite':
      return encoding2
    case '@autobonk/context-init':
      return encoding3
    case '@autobonk/role-def':
      return encoding4
    case '@autobonk/acl-entry':
      return encoding5
    case '@facebonk/profile':
      return encoding6
    case '@facebonk/profile-set':
      return encoding7
    case '@facebonk/blob':
      return encoding8
    default:
      throw new Error('Encoder not found ' + name)
  }
}

function getStruct(name, v = VERSION) {
  const enc = getEncoding(name)
  return {
    preencode(state, m) {
      version = v
      enc.preencode(state, m)
    },
    encode(state, m) {
      version = v
      enc.encode(state, m)
    },
    decode(state) {
      version = v
      return enc.decode(state)
    }
  }
}

const resolveStruct = getStruct // compat

export { resolveStruct, getStruct, getEnum, getEncoding, encode, decode, setVersion, version }
