// This file is autogenerated by the hyperdb compiler
/* eslint-disable camelcase */

import { IndexEncoder, c, b4a } from 'hyperdb/runtime'
import { version, getEncoding, setVersion } from './messages.js'

const versions = { schema: version, db: 1 }

// '@autobonk/invite' collection key
const collection0_key = new IndexEncoder([
  IndexEncoder.BUFFER
], { prefix: 0 })

function collection0_indexify (record) {
  const a = record.id
  return a === undefined ? [] : [a]
}

// '@autobonk/invite' value encoding
const collection0_enc = getEncoding('@autobonk/invite/hyperdb#0')

// '@autobonk/invite' reconstruction function
function collection0_reconstruct (schemaVersion, keyBuf, valueBuf) {
  const key = collection0_key.decode(keyBuf)
  setVersion(schemaVersion)
  const state = { start: 0, end: valueBuf.byteLength, buffer: valueBuf }
  const type = c.uint.decode(state)
  if (type !== 0) throw new Error('Unknown collection type: ' + type)
  collection0.decodedVersion = c.uint.decode(state)
  const record = collection0_enc.decode(state)
  record.id = key[0]
  return record
}
// '@autobonk/invite' key reconstruction function
function collection0_reconstruct_key (keyBuf) {
  const key = collection0_key.decode(keyBuf)
  return {
    id: key[0]
  }
}

// '@autobonk/invite'
const collection0 = {
  name: '@autobonk/invite',
  id: 0,
  version: 1,
  encodeKey (record) {
    const key = [record.id]
    return collection0_key.encode(key)
  },
  encodeKeyRange ({ gt, lt, gte, lte } = {}) {
    return collection0_key.encodeRange({
      gt: gt ? collection0_indexify(gt) : null,
      lt: lt ? collection0_indexify(lt) : null,
      gte: gte ? collection0_indexify(gte) : null,
      lte: lte ? collection0_indexify(lte) : null
    })
  },
  encodeValue (schemaVersion, collectionVersion, record) {
    setVersion(schemaVersion)
    const state = { start: 0, end: 2, buffer: null }
    collection0_enc.preencode(state, record)
    state.buffer = b4a.allocUnsafe(state.end)
    state.buffer[state.start++] = 0
    state.buffer[state.start++] = collectionVersion
    collection0_enc.encode(state, record)
    return state.buffer
  },
  trigger: null,
  reconstruct: collection0_reconstruct,
  reconstructKey: collection0_reconstruct_key,
  indexes: [],
  decodedVersion: 0
}

// '@autobonk/writer' collection key
const collection1_key = new IndexEncoder([
  IndexEncoder.BUFFER
], { prefix: 1 })

function collection1_indexify (record) {
  const a = record.key
  return a === undefined ? [] : [a]
}

// '@autobonk/writer' value encoding
const collection1_enc = getEncoding('@autobonk/writer/hyperdb#1')

// '@autobonk/writer' reconstruction function
function collection1_reconstruct (schemaVersion, keyBuf, valueBuf) {
  const key = collection1_key.decode(keyBuf)
  setVersion(schemaVersion)
  const state = { start: 0, end: valueBuf.byteLength, buffer: valueBuf }
  const type = c.uint.decode(state)
  if (type !== 0) throw new Error('Unknown collection type: ' + type)
  collection1.decodedVersion = c.uint.decode(state)
  const record = collection1_enc.decode(state)
  record.key = key[0]
  return record
}
// '@autobonk/writer' key reconstruction function
function collection1_reconstruct_key (keyBuf) {
  const key = collection1_key.decode(keyBuf)
  return {
    key: key[0]
  }
}

// '@autobonk/writer'
const collection1 = {
  name: '@autobonk/writer',
  id: 1,
  version: 1,
  encodeKey (record) {
    const key = [record.key]
    return collection1_key.encode(key)
  },
  encodeKeyRange ({ gt, lt, gte, lte } = {}) {
    return collection1_key.encodeRange({
      gt: gt ? collection1_indexify(gt) : null,
      lt: lt ? collection1_indexify(lt) : null,
      gte: gte ? collection1_indexify(gte) : null,
      lte: lte ? collection1_indexify(lte) : null
    })
  },
  encodeValue (schemaVersion, collectionVersion, record) {
    setVersion(schemaVersion)
    const state = { start: 0, end: 2, buffer: null }
    collection1_enc.preencode(state, record)
    state.buffer = b4a.allocUnsafe(state.end)
    state.buffer[state.start++] = 0
    state.buffer[state.start++] = collectionVersion
    collection1_enc.encode(state, record)
    return state.buffer
  },
  trigger: null,
  reconstruct: collection1_reconstruct,
  reconstructKey: collection1_reconstruct_key,
  indexes: [],
  decodedVersion: 0
}

// '@autobonk/context-init' collection key
const collection2_key = new IndexEncoder([
  IndexEncoder.BUFFER
], { prefix: 2 })

function collection2_indexify (record) {
  const a = record.creatorKey
  return a === undefined ? [] : [a]
}

// '@autobonk/context-init' value encoding
const collection2_enc = getEncoding('@autobonk/context-init/hyperdb#2')

// '@autobonk/context-init' reconstruction function
function collection2_reconstruct (schemaVersion, keyBuf, valueBuf) {
  const key = collection2_key.decode(keyBuf)
  setVersion(schemaVersion)
  const state = { start: 0, end: valueBuf.byteLength, buffer: valueBuf }
  const type = c.uint.decode(state)
  if (type !== 0) throw new Error('Unknown collection type: ' + type)
  collection2.decodedVersion = c.uint.decode(state)
  const record = collection2_enc.decode(state)
  record.creatorKey = key[0]
  return record
}
// '@autobonk/context-init' key reconstruction function
function collection2_reconstruct_key (keyBuf) {
  const key = collection2_key.decode(keyBuf)
  return {
    creatorKey: key[0]
  }
}

// '@autobonk/context-init'
const collection2 = {
  name: '@autobonk/context-init',
  id: 2,
  version: 1,
  encodeKey (record) {
    const key = [record.creatorKey]
    return collection2_key.encode(key)
  },
  encodeKeyRange ({ gt, lt, gte, lte } = {}) {
    return collection2_key.encodeRange({
      gt: gt ? collection2_indexify(gt) : null,
      lt: lt ? collection2_indexify(lt) : null,
      gte: gte ? collection2_indexify(gte) : null,
      lte: lte ? collection2_indexify(lte) : null
    })
  },
  encodeValue (schemaVersion, collectionVersion, record) {
    setVersion(schemaVersion)
    const state = { start: 0, end: 2, buffer: null }
    collection2_enc.preencode(state, record)
    state.buffer = b4a.allocUnsafe(state.end)
    state.buffer[state.start++] = 0
    state.buffer[state.start++] = collectionVersion
    collection2_enc.encode(state, record)
    return state.buffer
  },
  trigger: null,
  reconstruct: collection2_reconstruct,
  reconstructKey: collection2_reconstruct_key,
  indexes: [],
  decodedVersion: 0
}

// '@autobonk/role-def' collection key
const collection3_key = new IndexEncoder([
  IndexEncoder.STRING
], { prefix: 3 })

function collection3_indexify (record) {
  const a = record.name
  return a === undefined ? [] : [a]
}

// '@autobonk/role-def' value encoding
const collection3_enc = getEncoding('@autobonk/role-def/hyperdb#3')

// '@autobonk/role-def' reconstruction function
function collection3_reconstruct (schemaVersion, keyBuf, valueBuf) {
  const key = collection3_key.decode(keyBuf)
  setVersion(schemaVersion)
  const state = { start: 0, end: valueBuf.byteLength, buffer: valueBuf }
  const type = c.uint.decode(state)
  if (type !== 0) throw new Error('Unknown collection type: ' + type)
  collection3.decodedVersion = c.uint.decode(state)
  const record = collection3_enc.decode(state)
  record.name = key[0]
  return record
}
// '@autobonk/role-def' key reconstruction function
function collection3_reconstruct_key (keyBuf) {
  const key = collection3_key.decode(keyBuf)
  return {
    name: key[0]
  }
}

// '@autobonk/role-def'
const collection3 = {
  name: '@autobonk/role-def',
  id: 3,
  version: 1,
  encodeKey (record) {
    const key = [record.name]
    return collection3_key.encode(key)
  },
  encodeKeyRange ({ gt, lt, gte, lte } = {}) {
    return collection3_key.encodeRange({
      gt: gt ? collection3_indexify(gt) : null,
      lt: lt ? collection3_indexify(lt) : null,
      gte: gte ? collection3_indexify(gte) : null,
      lte: lte ? collection3_indexify(lte) : null
    })
  },
  encodeValue (schemaVersion, collectionVersion, record) {
    setVersion(schemaVersion)
    const state = { start: 0, end: 2, buffer: null }
    collection3_enc.preencode(state, record)
    state.buffer = b4a.allocUnsafe(state.end)
    state.buffer[state.start++] = 0
    state.buffer[state.start++] = collectionVersion
    collection3_enc.encode(state, record)
    return state.buffer
  },
  trigger: null,
  reconstruct: collection3_reconstruct,
  reconstructKey: collection3_reconstruct_key,
  indexes: [],
  decodedVersion: 0
}

// '@autobonk/acl-entry' collection key
const collection4_key = new IndexEncoder([
  IndexEncoder.BUFFER
], { prefix: 4 })

function collection4_indexify (record) {
  const a = record.subjectKey
  return a === undefined ? [] : [a]
}

// '@autobonk/acl-entry' value encoding
const collection4_enc = getEncoding('@autobonk/acl-entry/hyperdb#4')

// '@autobonk/acl-entry' reconstruction function
function collection4_reconstruct (schemaVersion, keyBuf, valueBuf) {
  const key = collection4_key.decode(keyBuf)
  setVersion(schemaVersion)
  const state = { start: 0, end: valueBuf.byteLength, buffer: valueBuf }
  const type = c.uint.decode(state)
  if (type !== 0) throw new Error('Unknown collection type: ' + type)
  collection4.decodedVersion = c.uint.decode(state)
  const record = collection4_enc.decode(state)
  record.subjectKey = key[0]
  return record
}
// '@autobonk/acl-entry' key reconstruction function
function collection4_reconstruct_key (keyBuf) {
  const key = collection4_key.decode(keyBuf)
  return {
    subjectKey: key[0]
  }
}

// '@autobonk/acl-entry'
const collection4 = {
  name: '@autobonk/acl-entry',
  id: 4,
  version: 1,
  encodeKey (record) {
    const key = [record.subjectKey]
    return collection4_key.encode(key)
  },
  encodeKeyRange ({ gt, lt, gte, lte } = {}) {
    return collection4_key.encodeRange({
      gt: gt ? collection4_indexify(gt) : null,
      lt: lt ? collection4_indexify(lt) : null,
      gte: gte ? collection4_indexify(gte) : null,
      lte: lte ? collection4_indexify(lte) : null
    })
  },
  encodeValue (schemaVersion, collectionVersion, record) {
    setVersion(schemaVersion)
    const state = { start: 0, end: 2, buffer: null }
    collection4_enc.preencode(state, record)
    state.buffer = b4a.allocUnsafe(state.end)
    state.buffer[state.start++] = 0
    state.buffer[state.start++] = collectionVersion
    collection4_enc.encode(state, record)
    return state.buffer
  },
  trigger: null,
  reconstruct: collection4_reconstruct,
  reconstructKey: collection4_reconstruct_key,
  indexes: [],
  decodedVersion: 0
}

// '@facebonk/profiles' collection key
const collection5_key = new IndexEncoder([
  IndexEncoder.STRING
], { prefix: 5 })

function collection5_indexify (record) {
  const a = record.id
  return a === undefined ? [] : [a]
}

// '@facebonk/profiles' value encoding
const collection5_enc = getEncoding('@facebonk/profile/hyperdb#5')

// '@facebonk/profiles' reconstruction function
function collection5_reconstruct (schemaVersion, keyBuf, valueBuf) {
  const key = collection5_key.decode(keyBuf)
  setVersion(schemaVersion)
  const state = { start: 0, end: valueBuf.byteLength, buffer: valueBuf }
  const type = c.uint.decode(state)
  if (type !== 0) throw new Error('Unknown collection type: ' + type)
  collection5.decodedVersion = c.uint.decode(state)
  const record = collection5_enc.decode(state)
  record.id = key[0]
  return record
}
// '@facebonk/profiles' key reconstruction function
function collection5_reconstruct_key (keyBuf) {
  const key = collection5_key.decode(keyBuf)
  return {
    id: key[0]
  }
}

// '@facebonk/profiles'
const collection5 = {
  name: '@facebonk/profiles',
  id: 5,
  version: 1,
  encodeKey (record) {
    const key = [record.id]
    return collection5_key.encode(key)
  },
  encodeKeyRange ({ gt, lt, gte, lte } = {}) {
    return collection5_key.encodeRange({
      gt: gt ? collection5_indexify(gt) : null,
      lt: lt ? collection5_indexify(lt) : null,
      gte: gte ? collection5_indexify(gte) : null,
      lte: lte ? collection5_indexify(lte) : null
    })
  },
  encodeValue (schemaVersion, collectionVersion, record) {
    setVersion(schemaVersion)
    const state = { start: 0, end: 2, buffer: null }
    collection5_enc.preencode(state, record)
    state.buffer = b4a.allocUnsafe(state.end)
    state.buffer[state.start++] = 0
    state.buffer[state.start++] = collectionVersion
    collection5_enc.encode(state, record)
    return state.buffer
  },
  trigger: null,
  reconstruct: collection5_reconstruct,
  reconstructKey: collection5_reconstruct_key,
  indexes: [],
  decodedVersion: 0
}

const collections = [
  collection0,
  collection1,
  collection2,
  collection3,
  collection4,
  collection5
]

const indexes = [
]

export default { versions, collections, indexes, resolveCollection, resolveIndex }

function resolveCollection (name) {
  switch (name) {
    case '@autobonk/invite': return collection0
    case '@autobonk/writer': return collection1
    case '@autobonk/context-init': return collection2
    case '@autobonk/role-def': return collection3
    case '@autobonk/acl-entry': return collection4
    case '@facebonk/profiles': return collection5
    default: return null
  }
}

function resolveIndex (name) {
  switch (name) {
    default: return null
  }
}
